name: tf-checks
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
jobs:
   complete-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    secrets: inherit
    with:
      working_directory: './examples/complete/service_principal_with_certificate'